version: '3.9'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1337:1337"
    environment:
      # Database - Supabase
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      
      # Node.js configuration - force IPv4 resolution
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      
      # Strapi
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-1337}
      
      # Admin panel - set a secure JWT secret
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      
      # Optional: App keys for encryption
      APP_KEYS: ${APP_KEYS}
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - strapi-network
    dns:
      - 1.1.1.1
      - 8.8.8.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:1337', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  strapi-network:
    driver: bridge